### ISSUE TITLE
Inclusion Brush

### ISSUE THREAD

**Issue by KanchanIIT** [eozmen410/interactive_grabcut#1]
Hi, first of all, thanks for your great work.  
Requesting for extension of a new feature:  could you please add an inclusion brush, the drawing brush is for exclusion. But for some cases, it's very much needed to include some part in the segmentation. I am trying to integrate that part but as being naive to JS not able to add that. 
Thanks in advance for your help.

**Comment by eozmen410** [comment]
Hi, thanks for your note! I added another canvas (the bottom canvas) on the second column that you can use to indicate foreground for inclusion. 
Because of the order in which the background and foreground lines are applied on the backend, if you indicate both foreground and background for the same pixel, it will be interpreted as background.
Hope this helps!

**Comment by KanchanIIT** [comment]
Thanks  @eozmen410 for your help, it's working perfectly fine.

**Comment by KanchanIIT** [comment]
Hi eozmen410, 
    Thanks for your modification. I am sorry to raise another issue. In the modification, although in the canvas we are able to draw the foreground line, in backend the  grabcut_drawing() is not getting any input to operate. while there is no line in background and foreground canvas, fg_drawing, bg_drawing both are empty in grabcut_drawing() function, which is natural. But fg_drawing is still empty after drawing the foreground line. It's getting the same value while there are lines in the background canvas. Sorry for raising this issue as I am a novice for JS otherwise I would have change the code and send you a push request. please have a look at the code.

**Comment by KanchanIIT** [comment]
I think at this line https://github.com/eozmen410/interactive_grabcut/blob/master/static/js/grabcut.js#L354
it would be 
 'lines' : **fg_lines**,
instead of 
 'lines' : **lines**,

**Comment by eozmen410** [comment]
You're right, sorry for the inconvenience, I must have not pushed the most updated version last time. I pushed the code with the change. Hope it helps, and let me know if there are any other issues!
